#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

get_package_changes () {
  local CURRENT_BRANCH
  CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

  git diff HEAD~1..HEAD~0 -- "origin/$CURRENT_BRANCH" package.json
}

has_package_changes () {
  [ ! -z "$(get_package_changes)" ]
}

if has_package_changes;
then
  npx cross-env DEBUG=@sequencemedia/hooks* node .husky/post-commit.mjs
fi
