#!/bin/sh

get_package_changes () {
  local CURRENT_BRANCH

  CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

  git diff HEAD~1..HEAD~0 -- "origin/$CURRENT_BRANCH" package.json
}

has_package_changes () {
  [ ! -z "$(get_package_changes)" ]
}

if has_package_changes;
then
  git clone https://github.com/sequencemedia/hooks.git .husky/hooks
  npx cross-env DEBUG=@sequencemedia/hooks* node .husky/hooks/post-commit.mjs
  rm -rf .husky/hooks
fi
